apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: dockerhub-secret
  namespace: kube-system
spec:
  encryptedData:
    .dockerconfigjson: AgBQvilNAjn1Ws/z5wIkawpZ26/R2NaYQG/UuKF34+1ho6thNx/yf2wUofMdVSE8JAd5hp7OZiYkvmUR6KYcEinW9L+UpArAykD0bsf2uSOPeAa/Prsvwj2EGNGM6jS6/QtC8xcJrwFdYLBlyjEYMSHdQF4AmQhq27tGu0pomcW6HT594HlHjPWkI9A5Hc6x/AWR3lw4uGWSx3EvF/cxMh5TVWXR4yro5sROICMXZV3DFo/Xvx8KvI7cdKz90CrIBhS81fSriQLvkvsLpOqFQeI/9wJoyCFIpA8bC3emWD0EXT5KDRaw71kmL7njli63MvtX6Mb2cbOzDREelHlucVY47RcP5PQCTEwEhpD4Vx1w/hgyMuEdclS2KySbrSjnjO+yXJABYmvaaw1UA1rf85/s+C8G0EBNgLXSqme+sPJBlp/0xtMv/nAc6miuMJuYKchAnaoINfFoGKI2Bxar4/GQKjsENtL2X/56L+OgwNlM8kkTg6LHCS52xrB55WOBBbxPDwoGFIHPMav5lffZDlKVAyK8U/osFsj5S1f4EzJAW/26a2M8YnBeyRSTPjy9dCd4lvVBwyhV0TIP0HnRNt5B4huVitvVEWpVjrW9q1q6oOv7oZkTm46tt2M/XVJkHUojiodT3UkGl+FpQt+JZEClicbbDthJBvTWyr+TUgL6Nh5JcxZzdWa47vcn5sohnFUTvd63oFFmxCiemAub6zLVv4qU1cbDOCLitET6vmBsIjphoUbTt70560tHpU/zdfXgEzQTsQojasDqpe01GP0zbUjNnmdTHriKdwsXlBe8ACnGBjwXms+1ckpBMNOMybWITMYHTC16ISWcCgHFDnl2B41XMMipGjyoY6Cg+txiwBw+kTDo4sHFyHWBio2oPY+PDWPMjTAJLWTWgHo1W5VGjmm4VgU8M2Ms/AA=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: dockerhub-secret
      namespace: kube-system
    type: kubernetes.io/dockerconfigjson

