apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgApSY/E4IzJOLUNjatDtBFXi3DnsM9agEDPtaus3fHNoitmYK3pOg/xM3TSxguXAtEm6C/cyikWLp1qnAuBTx34OLh9n41h1u0EQRWpeEQfZtOG5rY5zao+z4o64+0oBKPysVQGGV26PFfmA4gQjGlivNSs1z6B7+tuJm0yN7i/mCflsFnM+B2s51xkUM3KvDmLoJxaTV6Iy2GsuG1uhE7IvHfA2chUxYMLRiNhf0qBotJcX3l9ei2F2bE4biZIC2SfxG8VLjmeWvUhBNmIDHPP8mhUJAInSDC2sSg34jnWl+h9dO4zWdBSd/pRnaoFDMfWCjiG6K3vXXGTw5xdYethSPw+/OxsrriN1cXeuXsYl+ukYRpomh4NHlqqT5/rpOVeqTdVlKtWsncMocZfDumxyL3xhoHZnk2l55ExzwwS9aMFO00WjVcqwhN31/k2wsdLmfG7XxJquq5in9BjkBpmNaNFSDDYKyRVsAY8TL8FhsiIi0wA6dnzSSIM/znOvX7U9HfshcreWFXQRLB8BOrygqjGtS8OPuRzhzexc4b+VbDTU09XvZQFZh7Yn45aR33msz6CmzLRfNaWpLtyAiOgVhBnbt4AG8XW+OeB5bpbw7CCCdhuBeqMhweL4vW1QjoT/GzoEQvwizNu8PtNBAXyV4tLf8Zr0ALV0tJWTcIhF4Y8oeHH13IR7Ng47xqsClXkpr7Pz+khinkKnRLY3LhPSaZwSoRX6RFZ6Nl9yPBE6sAWx202tMeklITCeQ8qcx696DMjmRpoKXMlqfEL1SR3wa2nAK4r+gaft3m0iT9kT3hZplvsf6BafH5M27HaRG0YU7XgAXYojoY7ecbdrvVmOkfNA8rThpAedSS91ko2InlbypjEIFRadlHnCxfkd+Fn5Te3Nrn0cas4OUdjOeVVLDj8ieBlzcSqtKXP
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: dockerhub-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

