apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgCK5bk6DHg/ElvzqoVOvuVycQoo3zNpzO51cPAWKGRfOiTveOpWgtUqZtGR/ghSY7jyAWurmUH6gLMzCSpYgkP7I/c+PpLi1mdjzXIC2cDmlGxV7jnYF1wcn9nMjkes7ZaleEdXnE2Lqg+HWmExpxz3qNMpPdoNBmazUVQeOpvdB5ethoOCNeQsQLEPqP2gw6fjaIAlRXu6UVIpyXWUsCDuUB2S4ASoVXwGQZtXCT8tCWwGOPqM2Tzlqk8gaEAIaSqwjW5XIPP8Ozd0Z/CEskQAHEm+gNgmySBOGERUUOwZBqoeNWk5OhDu14ljHIpsyz3B9omno5SGnMxreWrO+5bblVWdTqNf3bjoCDY2BNLi70VF0rQhqETXoaa+/6FmaROKHLrcs5OIEJWUzE/GXreEfzK8i/qo2uv6mPpjZ+4STpX4t2ljMVzNZUn9J56WrRtUKeaw6d1kGr/++SKSvIRGPa/7guhd4zDZZ8cLp1MxZDTu8DrcP4yH/mkFHvFZgWDszvdr+VMtdpaoW/v1pgN9b+Y7V4iQyMLBBuGqXV6XQ5wzV3Ojk6MxuzOhvxBtxqTm6kPCYqCiWGYv87IHfypta7pLjgkUDn/rsjkUAqCIijKSSGdS4Z7QG/hHWSPYOh3YpbyVmiukEgE+qg+8xr/Nlhh05gVx15BZD2bg2BJBWiVDFfNAMmcKtd79z3AXpc79buMmjIL6xgLgO5qbZYZiHfjY5cfYU4hUD+sKh0z9n+9fr/QEy2jWuT0ZXF+nVOv20TPhqeVbzjC7Hg/8et/JXc7FgNn3fICrbd5rFu+ONKxbI/XvRWzWGZxL+vuYJrPujyPhXyQ3h7PhMVqH2gahhmCbl5bip8CXW1oXlJ3rIvjEOQ8LZK1tHHllA/sie8xk4Ih2Lvv/jztqDe0czx2xFaahy6oXRJvx4yA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: dockerhub-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

